### ISSUE TITLE
配置使用失败

### ISSUE THREAD

**Issue by wss-git** [fanzhe328/fc-layer#3]
问题1: 指向地址404
<img width="752" alt="image" src="https://github.com/user-attachments/assets/b034e82d-f60a-427e-b375-9cff32d671d0" />

问题2: 按照文档中的 arn 报错 The layer version is not found. LayerName: Puppeteer-Lib , Version:1.

https://github.com/fanzhe328/fc-layer/tree/main/layers/puppeteer-lib 

填写内容：acs:fc:cn-hangzhou:1940309364339785:layers/Puppeteer-Lib/versions/1

**Comment by fanzhe328** [comment]
fixed
